spring:
  application:
    name: commerce_site
    instance-id: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ecommerce_site
    username: root
    password: 8cfv67b67af12zxc
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: validate
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
      ddl-auto: none
    open-in-view: false
    defer-datasource-initialization: false
  flyway:
    enabled: true
    url: jdbc:mysql://localhost:3306/ecommerce_site
    user: root
    password: 8cfv67b67af12zxc
    baseline-on-migrate: true
    locations: classpath:db/migration/mysql
  jackson:
    property-naming-strategy: SNAKE_CASE
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9090/realms/oauth2/protocol/openid-connect/certs
          issuer-uri: http://localhost:9090/realms/oauth2
server:
  port: 8080
  forward-headers-strategy: framework
springdoc:
  version: v1.0.0
  api-docs:
    path: /api-docs/json
  default-produces-media-type: application/json;charset=UTF-8
  default-consumes-media-type: application/json;charset=UTF-8
  server-url: http://localhost:8080
oauth:
  keycloak:
    realm: oauth2
    auth-server-url: http://localhost:9090
    credentials:
      client: oauth2-client-app
      secret: 6buMCUOwLIjBhRE6oJ7TNklkIhPqyCl5
    grant-type: authorization_code
    uri:
      redirect: http://localhost:8080/auth/callback
      token: http://localhost:9090/realms/oauth2/protocol/openid-connect/token
    api-key: klzx98c7vadq34tkdjfhgq3#@$adfg!dfax-n-4c
auth:
  exclude:
    post:
      - /users/keycloak/webhook
      - /partners/keycloak/webhook
      - /partners
    get:
      - /auth/**
    web:
      - /swagger-ui/**
      - /api-docs/**