spring:
  application:
    name: commerce_site
    instance-id: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ecommerce_site
    username: root
    password: 8cfv67b67af12zxc
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
      ddl-auto: none
    open-in-view: false
  jackson:
    property-naming-strategy: SNAKE_CASE
server:
  port: 8080
  forward-headers-strategy: framework
springdoc:
  version: v1.0.0
  api-docs:
    path: /api-docs/json
  default-produces-media-type: application/json;charset=UTF-8
  default-consumes-media-type: application/json;charset=UTF-8
  server-url: http://localhost:8080