spring:
  application:
    name: commerce_site
    instance-id: 0
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
      ddl-auto: none
    open-in-view: false
  jackson:
    property-naming-strategy: SNAKE_CASE
server:
  port: 8080
  forward-headers-strategy: framework
